// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZICufUL5B3naM-j20D3AwFkdH3gLALH4',
    appId: '1:55629383914:web:af6ce5af637f98acd3ef93',
    messagingSenderId: '55629383914',
    projectId: 'workout-tracker-a1e7a',
    authDomain: 'workout-tracker-a1e7a.firebaseapp.com',
    storageBucket: 'workout-tracker-a1e7a.firebasestorage.app',
    measurementId: 'G-V29S3W4996',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA6VVgv--GjRxqb5_S0TH-aCz_A-ZvtwQ',
    appId: '1:55629383914:android:959ef85546812f6dd3ef93',
    messagingSenderId: '55629383914',
    projectId: 'workout-tracker-a1e7a',
    storageBucket: 'workout-tracker-a1e7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZjGILppWOlzoj82Gs-MX-Rktrk47mgM',
    appId: '1:55629383914:ios:520b4111ef33cfcfd3ef93',
    messagingSenderId: '55629383914',
    projectId: 'workout-tracker-a1e7a',
    storageBucket: 'workout-tracker-a1e7a.firebasestorage.app',
    iosBundleId: 'com.example.workoutTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZjGILppWOlzoj82Gs-MX-Rktrk47mgM',
    appId: '1:55629383914:ios:520b4111ef33cfcfd3ef93',
    messagingSenderId: '55629383914',
    projectId: 'workout-tracker-a1e7a',
    storageBucket: 'workout-tracker-a1e7a.firebasestorage.app',
    iosBundleId: 'com.example.workoutTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZICufUL5B3naM-j20D3AwFkdH3gLALH4',
    appId: '1:55629383914:web:d2ed50e19381f11bd3ef93',
    messagingSenderId: '55629383914',
    projectId: 'workout-tracker-a1e7a',
    authDomain: 'workout-tracker-a1e7a.firebaseapp.com',
    storageBucket: 'workout-tracker-a1e7a.firebasestorage.app',
    measurementId: 'G-H6HSY1C6JL',
  );

}